### ISSUE TITLE
Cleanup and fine tune new gitlab / k8s setup

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1055]
## Tasks

 - [x] Setup Gitlab to run tests (see Jenkinsfile for reference)
   - [x] flake8
   - [x] Django tests
   - [x] Acceptance tests 
 - [x] Ping NewRelic on deployments (see Jenkinsfile for reference)
 - [x] Update Mana with deployment instructions
 - [x] Delete merged / not needed branches from `snippets-service` and `snippets-config` on both 
     - [x] GitHub
     - [x] GitLab
 - [-] Setup HPA for `snippets-prod-web` moved to https://github.com/mozmeao/infra/issues/1138
   ~~Note: It seems like we have HPA setup on both clusters *but* I cannot find any reference of it in `snippets-config`, so I assume that this the HPA setup by Deis. If that's the case we need configuration in `snippets-config` for the HPA.~~
 - [x] `static/revision.txt` is empty. Needs fixing, see also #1031. Make sure that  https://whatsdeployed.io/s/088/mozmeao/snippets-service works
 - [x] Remove Jenkins Pipeline
 - [x] Remove deprecated comments from `.gitlab-ci.yml`
   - [x] https://github.com/mozmeao/snippets-service/blob/master/.gitlab-ci.yml#L13 
   - [x] https://github.com/mozmeao/snippets-service/blob/master/.gitlab-ci.yml#L30 and     
   - [x] https://github.com/mozmeao/snippets-service/blob/master/.gitlab-ci.yml#L63
 - [x] Merge `prod` and `admin` configurations in https://github.com/mozmeao/snippets-service/blob/master/.gitlab-ci.yml#L36
 - [x] Cleanup branch configuration in https://github.com/mozmeao/snippets-service/blob/master/.gitlab-ci.yml

**Comment by glogiotatidis** [comment]
Hey @jgmize @jpetto can you help with these pending tasks to complete the migration to gitlab ci?

**Comment by jgmize** [comment]
Thanks for identifying these issues @glogiotatidis. I'll work with @jpetto to get them addressed.

**Comment by glogiotatidis** [comment]
Created https://github.com/mozmeao/infra/issues/1138 for HPA setup.

Other requests were fixed. Thanks again @jpetto @jgmize :cake:
