### ISSUE TITLE
Create view to redirect clients to the correct pregenerated bundle

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1112]
## Why

Because custom Firefox builds alter the %CHANNEL% variable we cannot directly point to a single file. Instead we will deploy Lambda@Edge functions which will convert the request URL to an expected format, which is practically change %CHANNEL%-* to %CHANNEL%

#### List of highly used settings for %CHANNEL%
- release
- release-cck-ubuntu
- beta
- release-cck-mozillaonline
- nightly
- nrelease-cck- âmintâ
- aurora
- 641165 release-cck-yahoo
- release-cck-archlinux
- release-cck-mint
- release-cck-fedora
- release-cck-euballot

This must return the actual channel (`release`, `beta`, etc)

## Tasks
- [x] Remove deprecated Lambda functions from snippets stage cdn
- [x] What happens with redirects which 404? Maybe that generates a lot of traffic? We either implement #1113 or we check on the app level if file exists in S3 and if not we return 204 instead of 302. Or we do nothing is client is fine with 404? We handle that on the CDN level. See #1113 for comments.
- [x]  Confirm that we can change Snippets request URL for all Quantum versions via Normandy
- [x] Create `empty.json` on snippets-prod s3 bucket with Content-type and Cache-contorl headers

**Comment by glogiotatidis** [comment]
Hey @metadave 

If I'm not mistaken I remember you offering to setup me up with some TF to create a Lambda @ Edge function to use with the Snippets CloudFront Distribution.

I need a python  function at the Origin Request level (https://docs.aws.amazon.com/lambda/latest/dg/lambda-edge.html) for distribution d31g0e3nurrasj.cloudfront.net (stage) and another for d228z91au11ukj.cloudfront.net (prod)

Is this something you can do?

Thanks!

**Comment by metadave** [comment]
> Is this something you can do?

yes, but it looks like there isn't any TF automation for the stage CDN. I'll have to see if I can import it and go from there.

**Comment by metadave** [comment]
WIP here: https://github.com/mozmeao/infra/pull/1159

**Comment by glogiotatidis** [comment]
We will go ahead and implement this as a Django view for the first iteration which is better known and won't generate new costs. 

Will update snippets stage CDN to remove deprecated lambdas

**Comment by pmac** [comment]
It sounds like it is possible to skip snippets-service all together and have the clients just try to fetch the bundle directly from CloudFront right? If we'd like to be able to do than then I like your last idea about the custom 404. If we don't want to do that and would rather stick with clients getting redirected from the service then caching the existence seems fine. Maybe just an `s3_exists()` helper function wrapped in a `functools.lru_cache` decorator.

**Comment by glogiotatidis** [comment]
> It sounds like it is possible to skip snippets-service all together and have the clients just try to fetch the bundle directly from CloudFront right?

Sort of. Clients still need to reach the snippets-service to translate their request URL to a pregen bundle URL.

e.g. 
`https://snippets.cdn.mozilla.net/6/Firefox/69.0.1/20190917135527/WINNT_x86_64-msvc/en-us/release/Windows_NT%206.1//default/default/`

to

`https://snippets.cdn.mozilla.net/6/Firefox/en-us/release/default.json`


My initial idea was that clients will indeed hit CF directly but this is not possible b/c different builds may use different channel names like the ones listed in the original post.

**Comment by pmac** [comment]
Yeah. I was just wondering if it were possible to do that new URL creation on the client side. If not then I think dealing with the missing bundles in the app is probably fine.

**Comment by glogiotatidis** [comment]
I experimented with caching the `s3_exists()` result to redis and it performs better than before but still it generates a lot of I/O wait, especially for frankfurt which is away from the bucket location. 

And then I figured out that S3 bucket actually returns `403` instead of `404` because we disallow directory listing, thus when a file does not exist it will return 403 Forbidden. I then tried using custom error pages on the CloudFront level to return an empty json file when Origins return 403 and it works like a charm!

So to recap this is what happens with this solution:
 - snippets-service constructs a URL and always redirects clients to CDN / S3 
 - If file exists, users get back the file
 - If file doesn't exist, users get back a custom CF page with 200 status code and empty json.
 - Actual 404 pages, do work as before.

I like this approach the best, as it combines the best of all worlds with the best performance: Small initial tests on fran-prod  show that the Memory and CPU usage drops to less than half and the avg response time drops to sub 10ms. 

I created a [PR with the code updates](https://github.com/mozmeao/snippets-service/pull/1210) and another with the [CDN updates](https://github.com/mozmeao/infra/pull/1178) (for stage only for now).

You can try out this solution on staging

Returns empty json because bundle does not exist. Notice the `X-Cache: Error from cloudfront` header:
`curl -L -s -I  "https://snippets.allizom.org/6/Firefox/69.0.1/20190917135527/WINNT_x86_64-msvc/it/release/Windows_NT%206.1/default/default/"`

Returns bundle
`curl -L -s -I  "https://snippets.allizom.org/6/Firefox/69.0.1/20190917135527/WINNT_x86_64-msvc/en-us/release/Windows_NT%206.1/default/default/" `

Returns 404

`curl -L -s -I  "https://snippets.allizom.org/404"`

**Comment by glogiotatidis** [comment]
What do you think @pmac?

**Comment by pmac** [comment]
Looks perfect! Nice work! r+ 👍

**Comment by glogiotatidis** [comment]
Woot, thanks! I'll update CDN prod and enable pregen bundles on prod tomorrow!

**Comment by glogiotatidis** [comment]
Deployed to production, everything works as expected.

Adding here some numbers and graphs for celebration :man_dancing: 

Response time 

![Screenshot_2019-10-30 snippets-prod-frankfurt - New Relic](https://user-images.githubusercontent.com/584352/67844343-41926700-fb06-11e9-8992-4b056f67d7ac.png)

CPU / Mem usage halved

![Screenshot_2019-10-30 snippets-prod-frankfurt - New Relic(1)](https://user-images.githubusercontent.com/584352/67844445-6ab2f780-fb06-11e9-82ad-761a63825ddf.png)
