### ISSUE TITLE
Squash migrations

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1465]
## Task list
 - [x] Generate squashed migration
 - [ ] Push all the way to production
 - [ ] Remove old migration files.
