### ISSUE TITLE
Simplify snippets-prod deployments

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#1468]
Replace snippets prod deployments with minimal python apps that redirect to the correct pregen bundle. 

## Task list
 - [x] Deploy to frankfurt and oregon
 - [x] Cleanup snippets-config snippets-prod
 - [x] Evaluate frankfurt RDS replica removal
 - [ ] Eval Lambda failovers
