### ISSUE TITLE
Decom old about:home code, snippets and templates

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#505]
The last snippets on the service related to the old about:home page where disabled on Feb 14th 2018. Given that SHIELD is also running "firefox version too old, please upgrade" snippets, can we proceed to remove code, templates and snippets from the service?

This will help with code maintenance, tech debt and speed of the site. 

In case there's strong interest to save the data of the old snippets, e.g. for reference we can work on different solutions.

# Task List
 - [ ] Remove DMS "Disable Snippets" 
   - [ ] [Prod](https://deadmanssnitch.com/snitches/a4b6a2c25f)
   - [ ] [Stage](https://deadmanssnitch.com/snitches/16868e094e)
   - [ ] [Dev](https://deadmanssnitch.com/snitches/e3103977fb)

**Comment by glogiotatidis** [comment]
@bensternthal can you please check if we can proceed with this?

**Comment by glogiotatidis** [comment]
See also #545

**Comment by glogiotatidis** [comment]
I think we'll let this be for 2019. 

/remind me to check in Jan 20th 2020

**Comment by glogiotatidis** [comment]
The time has come 
![image](https://user-images.githubusercontent.com/584352/75321536-a2923780-5879-11ea-9e4c-28fd859536f4.png)

**Comment by glogiotatidis** [comment]
Again on life support. Let's discuss in Q4.

/remind me in October

**Comment by glogiotatidis** [comment]
restarted with convo. 

/remind me in a week

**Comment by glogiotatidis** [comment]
Well, this is complete! 2.5 years after filing this bug.

6 years of snippets history code. They served us well, I can't really remember any significant downtime or code related issues.  :metal: :tada:
