### ISSUE TITLE
Tracker: ASR Performance

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#679]
ASR makes excessive requests to the snippets service. This issue tracks the work related to improving its behavior.

 * [x]  Implement ASR persistent storage + caching for remote endpoints - [bug 1433243](https://bugzilla.mozilla.org/show_bug.cgi?id=1433243)
 * [x]  Only load ASR snippets when experiment is enabled - [bug 1485339](https://bugzilla.mozilla.org/show_bug.cgi?id=1485339)

Also we want to confirm with the AS team that 

 - [x] ASR fetches updates from Snippets every 4 hours and caches the response for 4 hours.

**Comment by glogiotatidis** [comment]
Persistent storage moved to Fx64

**Comment by glogiotatidis** [comment]
Latest update is that code has landed in AS and the team will try to uplift to 63.
