### ISSUE TITLE
Correct migrated ASRSnippets to comply with new rules

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#860]
A portion of ASRSnippets migrated from Snippets will need to be further edited to comply to the new Snippet rules. 

Errors are related to the use of HTML  which is no longer allowed to be used.

Currently we have a total of `1111` ASRSnippets that need to be further edited. 

Some edits we will be able to automated. Will update here with a list of edits to be done

 - [x] Migrate `&amp;` to `&`. Part of #854. About `800` snippets 
 - [x] Snippets with insecure links 
 - [x] Snippets using `version_lower_bound` or `version_upper_bound`
It's only the following snippets which are not published. Will talk with the team about this
  ```
9354 - 57-62 - not being migrated
9459 - 57 - fixed by removing the lower bound. it will always be greater than 57 
9484 - 62 - fixed by removing the lower bound. it will always be greater than 62
9354 - 57-63 - not being migrated
7719 - 45.0 - not being migrated
```
 - [x] ~~`MOCO_global_2018_f100_week6_utility_SUMO_newtab_activity_stream_DE_REL` and `MOCO_global_2018_f100_week6_utility_SUMO_newtab_activity_stream_DE_REL` hit MariaDB unique limit (truncates in 64 chars)~~ - only a local instance issue
 - [x] Remove `class="more"` from links in certain snippets or `target="_blank"` or other attributes that shouldn't be there. Taken care in https://github.com/mozmeao/snippets-service/pull/854/commits/38938aa2a7830614f85affb0c8ac41d6831d69d3
 - [x] Make sure that (at least Fundraising) snippets with `utm_params` are using correct links. See https://github.com/mozilla/activity-stream/pull/4579#issuecomment-442119813 See also #866
 - [x] Snippets with custom `text_color`, `background_color`, `button_color`, `button_background_color` need to be manually verified #836 
```python
snippets =  []
for snippet in Snippet.objects.all():
    data = json.loads(snippet.data)
    if data.get('button_color') or data.get('button_background_color') or data.get('text_color') or data.get('background_color'):
        snippets.append(snippet.id)

```
 - [x] Confirm that newsletter and s2d snippets have meaningful button on error page. see #862

**Comment by jkt230** [comment]
Definitely a P1 and we can work together on this.

**Comment by glogiotatidis** [comment]
Perfect, thanks @jkt230 

I checked everything but the last two points.
 - Can you check that custom buttons / colors work nicely?
 - and that Send to Device and Newsletter scene1 buttons have text which makes sense when it appears on the error page?

**Comment by jkt230** [comment]
- Can you check that custom buttons / colors work nicely?
We can only customize the scene 1 button right? 
Customizing is fine, what I noticed is that it doesn't have that nice default feature of when you hover over the button, the color changes slightly. I guess it's not a priority and hard to get that added in?

-and that Send to Device and Newsletter scene1 buttons have text which makes sense when it appears on the error page?
how do I get myself to that error page? I don't know how to test it - let me know, thanks!

**Comment by glogiotatidis** [comment]
>     * and that Send to Device and Newsletter scene1 buttons have text which makes sense when it appears on the error page?
>       how do I get myself to that error page? I don't know how to test it - let me know, thanks!

Well, that's difficult to get, because of who robust our systems are :) The error page features the `error_text` and next to that a button which is the same as in scene1 and its label is the `scene1_button_label` variable.

The problem here is that *if* some scene1 buttons have copy like `Learn More` those don't make much sense in the error page. In case of an error the user would read:

`Something went wrong. Please try again` and then the button label would be `Learn More`.

This makes a weird UX, so maybe we want to rethink copy of button labels for some snippets. Or maybe not, I just wanted to make sure that you know :)

So to your question: You can test by imagining the error page with `error_text` and a button with `scene1_button_label`.

**Comment by glogiotatidis** [comment]
Not blocking Fx64
