### ISSUE TITLE
Remove dependency on DynamicField

### ISSUE THREAD

**Issue by glogiotatidis** [mozmeao/snippets-service#940]
The project has a dependency on [MariaDB's DynamicField](https://django-mysql.readthedocs.io/en/latest/model_fields/dynamic_field.html).

Evaluate its replacement, probably with a simple django model fields, to remove the MariaDB dependency.\

Used in 
 - https://github.com/mozmeao/snippets-service/blob/master/snippets/base/models.py#L569
 - https://github.com/mozmeao/snippets-service/blob/master/snippets/base/models.py#L288

Migration Plan:
 - [x] Set `ENABLE_ADMIN=False` on `snippets-admin`
 - [x] Backup
 - [x] Capture the responses for `en-US`, `de`, `fr` on `release` for both `ASR` and `AS` snippets
 - [x] Merge and push all the way to production #950:
    - Generates all the new fields and migrates data to the new fields.
    - Does not remove anything yet
 - [x] Validate the responses for `en-US`, `de`, `fr` on `release` for both `ASR` and `AS` snippets
 - [x] Backup again
 - [x] Merge and push all the way to production #955 
 - [x] Merge and push all the way to production #956
 - [x] Set `ENABLE_ADMIN=True` on `snippets-admin`

**Comment by glogiotatidis** [comment]
Moving off DynamicField will enable us to move off MariaDB and its unicode incompatibilities. See also #910

**Comment by glogiotatidis** [comment]
We discussed and agreed with @jgmize to prioritize this work so we can unlock the options of GCP and Postgres

**Comment by glogiotatidis** [comment]
This was completed successfully.

For the record:
 - I exec-ed into a running pod
 - Run `./manage.py dump > dump.json` to get all the data
 - Run `export DATABASE_URL=postgresql://...`
 - `./manage.py migrate`
 - `./manage.py shell_plus` and `ContentType.objects.all().delete()`
 - `./manage.py load dump`

Then I used `deis` to redeploy with the new `DATABASE_URL`. 

Updated on all `dev`, `stage`, `admin`, `prod` frankfurt and oregon

**Comment by glogiotatidis** [comment]
Logged in / out from /admin, generated new bundles, everything appears to be working fine
